<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $fillable = [
        'name',
        'code',
        'slug',
        'snippets',
        'population',
        'gdp',
        'inflation',
        'corporate_tax',
        'interest_rate',
        'income',
        'personal_savings',
        'unemployment_rate',
        'labor_force',
        'income_tax',
        'gov_debt_to_gdp',
        'bank_reserves',
        'budget',
        'status'
    ];

    public $casts = [
        'snippets' => 'json',
        'population' => 'json',
        'inflation' => 'json',
        'corporate_tax' => 'json',
        'interest_rate' => 'json',
        'unemployment_rate' => 'json',
        'labor_force' => 'json',
        'income_tax' => 'json',
        'gdp' => 'json',
        'gov_debt_to_gdp' => 'json',
        'central_bank_balance_sheet' => 'json',
        'budget' => 'json',
    ];

    public function articles()
    {
        return $this->morphMany('App\Article', 'item');
    }

    public function registry()
    {
        return $this->morphOne('App\Registry', 'entry');
    }

    public static $topics = [
        'interest-rates',
        'economy',
        'culture'
    ];

  
    public static $countries = [
        "Afghanistan" => "afg",
        "Albania" => "alb",
        "Algeria" => "dza",
        "Andorra" => "and",
        "Angola" => "ago",
        "Antigua and Barbuda" => "atg",
        "Argentina" => "arg",
        "Armenia" => "arm",
        "Aruba" => "abw",
        "Australia" => "aus",
        "Austria" => "aut",
        "Azerbaijan" => "aze",
        "Bahamas" => "bhs",
        "Bahrain" => "bhr",
        "Bangladesh" => "bgd",
        "Barbados" => "brb",
        "Belarus" => "blr",
        "Belgium" => "bel",
        "Belize" => "blz",
        "Benin" => "ben",
        "Bermuda" => "bmu",
        "Bhutan" => "btn",
        "Bolivia" => "bol",
        "Bosnia and Herzegovina" => "bih",
        "Botswana" => "bwa",
        "Brazil" => "bra",
        "Brunei" => "brn",
        "Bulgaria" => "bgr",
        "Burkina Faso" => "bfa",
        "Burundi" => "bdi",
        "Cambodia" => "khm",
        "Cameroon" => "cmr",
        "Canada" => "can",
        "Cape Verde" => "cpv",
        "Cayman Islands" => "cym",
        "Central African Republic" => "caf",
        "Chad" => "tcd",
        "Chile" => "chl",
        "China" => "chn",
        "Colombia" => "col",
        "Comoros" => "com",
        "Democratic Republic of the Congo" => "cod",
        "Costa Rica" => "cri",
        "Croatia" => "hrv",
        "Cuba" => "cub",
        "Cyprus" => "cyp",
        "Czech Republic" => "cze",
        "Denmark" => "dnk",
        "Djibouti" => "dji",
        "Dominica" => "dma",
        "Dominican Republic" => "dom",
        "East Timor" => "tls",
        "Ecuador" => "ecu",
        "Egypt" => "egy",
        "El Salvador" => "slv",
        "Equatorial Guinea" => "gnq",
        "Eritrea" => "eri",
        "Estonia" => "est",
        "Ethiopia" => "eth",
        "Faroe Islands" => "fro",
        "Fiji" => "fji",
        "Finland" => "fin",
        "France" => "fra",
        "Gabon" => "gab",
        "Gambia" => "gmb",
        "Georgia" => "geo",
        "Germany" => "deu",
        "Ghana" => "gha",
        "Gibraltar" => "gib",
        "Greece" => "grc",
        "Greenland" => "grl",
        "Grenada" => "grd",
        "Guam" => "gum",
        "Guatemala" => "gtm",
        "Guinea Bissau" => "gnb",
        "Guinea" => "gin",
        "Guyana" => "guy",
        "Haiti" => "hti",
        "Honduras" => "hnd",
        "Hong Kong" => "hkg",
        "Hungary" => "hun",
        "Iceland" => "isl",
        "India" => "ind",
        "Indonesia" => "idn",
        "Iran" => "irn",
        "Iraq" => "irq",
        "Ireland" => "irl",
        "Isle of Man" => "imn",
        "Israel" => "isr",
        "Italy" => "ita",
        "Ivory Coast" => "civ",
        "Jamaica" => "jam",
        "Japan" => "jpn",
        "Jordan" => "jor",
        "Kazakhstan" => "kaz",
        "Kenya" => "ken",
        "Kiribati" => "kir",
        "Kosovo" => "xkx",
        "Kuwait" => "kwt",
        "Kyrgyzstan" => "kgz",
        "Laos" => "lao",
        "Latvia" => "lva",
        "Lebanon" => "lbn",
        "Lesotho" => "lso",
        "Liberia" => "lbr",
        "Libya" => "lby",
        "Liechtenstein" => "lie",
        "Lithuania" => "ltu",
        "Luxembourg" => "lux",
        "Macao" => "mac",
        "Macedonia" => "mkd",
        "Madagascar" => "mdg",
        "Malawi" => "mwi",
        "Malaysia" => "mys",
        "Maldives" => "mdv",
        "Mali" => "mli",
        "Malta" => "mlt",
        "Mauritania" => "mrt",
        "Mauritius" => "mus",
        "Mexico" => "mex",
        "Moldova" => "mda",
        "Monaco" => "mco",
        "Mongolia" => "mng",
        "Montenegro" => "mne",
        "Morocco" => "mar",
        "Mozambique" => "moz",
        "Myanmar" => "mmr",
        "Namibia" => "nam",
        "Nepal" => "npl",
        "Netherlands" => "nld",
        "New Caledonia" => "ncl",
        "New Zealand" => "nzl",
        "Nicaragua" => "nic",
        "Niger" => "ner",
        "Nigeria" => "nga",
        "North Korea" => "prk",
        "Norway" => "nor",
        "Oman" => "omn",
        "Pakistan" => "pak",
        "Palestine" => "pse",
        "Panama" => "pan",
        "Papua New Guinea" => "png",
        "Paraguay" => "pry",
        "Peru" => "per",
        "Philippines" => "phl",
        "Poland" => "pol",
        "Portugal" => "prt",
        "Puerto Rico" => "pri",
        "Qatar" => "qat",
        "Republic of The Congo" => "cog",
        "Romania" => "rou",
        "Russia" => "rus",
        "Rwanda" => "rwa",
        "Samoa" => "wsm",
        "Sao Tome and Principe" => "stp",
        "Saudi Arabia" => "sau",
        "Senegal" => "sen",
        "Serbia" => "srb",
        "Seychelles" => "syc",
        "Sierra Leone" => "sle",
        "Singapore" => "sgp",
        "Slovakia" => "svk",
        "Slovenia" => "svn",
        "Solomon Islands" => "slb",
        "Somalia" => "som",
        "South Africa" => "zaf",
        "South Korea" => "kor",
        "South Sudan" => "ssd",
        "Spain" => "esp",
        "Sri Lanka" => "lka",
        "Sudan" => "sdn",
        "Suriname" => "sur",
        "Sweden" => "swe",
        "Switzerland" => "che",
        "Syria" => "syr",
        "Taiwan" => "twn",
        "Tajikistan" => "tjk",
        "Tanzania" => "tza",
        "Thailand" => "tha",
        "Togo" => "tgo",
        "Tonga" => "ton",
        "Trinidad and Tobago" => "tto",
        "Tunisia" => "tun",
        "Turkey" => "tur",
        "Turkmenistan" => "tkm",
        "Uganda" => "uga",
        "Ukraine" => "ukr",
        "United Arab Emirates" => "are",
        "United Kingdom" => "gbr",
        "United States" => "usa",
        "Uruguay" => "ury",
        "Uzbekistan" => "uzb",
        "Vanuatu" => "vut",
        "Venezuela" => "ven",
        "Vietnam" => "vnm",
        "Yemen" => "yem",
        "Zambia" => "zmb",
        "Zimbabwe" => "zwe",
    ];
}
